/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK */

#ifndef _Included_com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK
#define _Included_com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zd_neliva_1android_1sdk_RK_1YOLOV5_1DET_1SDK_init
  (JNIEnv *, jclass);

/*
 * Class:     com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK
 * Method:    det
 * Signature: ([BII)[Lcom/zd/neliva_android_sdk/RK_YOLOV5_DET_SDK/RK_YOLOV5_Res;
 */
JNIEXPORT jobjectArray JNICALL Java_com_zd_neliva_1android_1sdk_RK_1YOLOV5_1DET_1SDK_det
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_zd_neliva_android_sdk_RK_YOLOV5_DET_SDK
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zd_neliva_1android_1sdk_RK_1YOLOV5_1DET_1SDK_deinit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
